pool:
  vmImage: "Ubuntu 16.04"

name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

steps:
  - task: ArtifactoryMaven@1
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'package'
      artifactoryResolverService: 'flightcentre-integration-artifactory'
      targetResolveReleaseRepo: 'flightcentre-integration-maven'
      targetResolveSnapshotRepo: 'flightcentre-integration-maven'
      artifactoryDeployService: 'flightcentre-integration-artifactory'
      targetDeployReleaseRepo: 'flightcentre-integration-maven'
      targetDeploySnapshotRepo: 'flightcentre-integration-maven'
      collectBuildInfo: true
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'